// <auto-generated />
namespace RestaurantEntity.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class menuMigration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(menuMigration));
        
        string IMigrationMetadata.Id
        {
            get { return "202206301730164_menuMigration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
